using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;

namespace RazerHelper
{
    internal sealed class FakeTextClipboard : ITextClipboard
    {
        internal string Value;internal bool HasNonText,FailWrite;internal int Writes;private long revision;
        public long Sequence{get{return revision;}}
        public bool OnlyText(){return !HasNonText;}
        public string ReadText(){return Value;}
        public void WriteText(string text){Writes++;Value=text;revision++;if(FailWrite){FailWrite=false;throw new IOException("fake partial clipboard failure");}}
        internal void UserCopy(string text){Value=text;revision++;}
    }
    internal sealed class FakeProcessorPolicy : IProcessorPolicy
    {
        internal Guid Active=Guid.NewGuid(); internal Guid Overlay=WindowsPower.Performance;
        internal readonly Dictionary<string,ProcessorPolicyState> States=new Dictionary<string,ProcessorPolicyState>();
        internal int Writes, FailAt, IgnoreAt; internal bool IgnoreRecovery;
        internal readonly List<Guid> Activations=new List<Guid>(); internal Action<int> AfterWrite;
        internal FakeProcessorPolicy(){States[Key(Active,true)]=new ProcessorPolicyState{Plan=Active,AC=true,Minimum=5,Maximum=100,Epp=20,Boost=2};States[Key(Active,false)]=new ProcessorPolicyState{Plan=Active,AC=false,Minimum=5,Maximum=100,Epp=90,Boost=2};}
        private static string Key(Guid plan,bool ac){return plan+":"+ac;}
        private ProcessorPolicyState State(Guid plan,bool ac){string key=Key(plan,ac);if(!States.ContainsKey(key))States[key]=new ProcessorPolicyState{Plan=plan,AC=ac,Minimum=5,Maximum=100,Epp=40,Boost=2};return States[key];}
        public ProcessorPolicyState Read(bool ac){return ReadPlan(Active,ac);}
        public ProcessorPolicyState ReadPlan(Guid plan,bool ac){var result=Store.Serializer().Deserialize<ProcessorPolicyState>(Store.Serializer().Serialize(State(plan,ac)));result.Overlay=Overlay;result.ActivePlan=Active;return result;}
        public void Write(Guid plan,bool ac,string name,int value)
        {
            Writes++;if(Writes==FailAt)throw new IOException("fake write failure");
            if(Writes!=IgnoreAt && !(IgnoreRecovery && Writes>1)){var s=State(plan,ac);if(name=="Minimum")s.Minimum=value;else if(name=="Maximum")s.Maximum=value;else if(name=="Boost")s.Boost=value;else if(name=="Epp")s.Epp=value;else throw new ArgumentException();}
            if(AfterWrite!=null)AfterWrite(Writes);
        }
        public void Activate(Guid plan){if(plan!=Active)throw new InvalidOperationException("unexpected plan switch");Activations.Add(plan);}
    }
    internal static partial class Tests
    {
        private static MacroDefinition CopyMacro(MacroDefinition macro){return Store.Serializer().Deserialize<MacroDefinition>(Store.Serializer().Serialize(macro));}
        private static ProcessorPolicyState CpuDesired(ProcessorPolicyState original,int max,int? epp){return new ProcessorPolicyState{Plan=original.Plan,ActivePlan=original.ActivePlan,AC=original.AC,Overlay=original.Overlay,Minimum=original.Minimum,Maximum=max,Boost=original.Boost,Epp=epp};}
        private static MacroDefinition Synapse(params Dictionary<string,object>[] events)
        {
            return SynapseImport.ConvertMacro(new Dictionary<string,object>{{"name","fixture"},{"guid",Guid.NewGuid().ToString()},{"delaySetting",0},{"appEngine",new Dictionary<string,object>{{"mouseMoveType","absolute"},{"events",events}}}});
        }
        private static Dictionary<string,object> Event(string type,params object[] fields){var result=new Dictionary<string,object>{{"type",type}};for(int i=0;i<fields.Length;i+=2)result[(string)fields[i]]=fields[i+1];return result;}
        private static byte[] V(ulong value){var result=new List<byte>();do{byte b=(byte)(value&127);value>>=7;if(value!=0)b|=128;result.Add(b);}while(value!=0);return result.ToArray();}
        private static uint MaskedCrc(byte[] data){uint crc=0xffffffff;foreach(byte x in data){crc^=x;for(int j=0;j<8;j++)crc=(crc>>1)^((crc&1)!=0?0x82f63b78u:0);}crc=~crc;return ((crc>>15)|(crc<<17))+0xa282ead8u;}
        private static byte[] Wal(ulong sequence,bool deleted,string value)
        {
            byte[] key=Encoding.UTF8.GetBytes("_https://synapse.invalid\0\x01synapseMacros"),text=Encoding.UTF8.GetBytes("\x01"+value);
            var data=new List<byte>();data.AddRange(BitConverter.GetBytes(sequence));data.AddRange(BitConverter.GetBytes((uint)1));data.Add(deleted?(byte)0:(byte)1);data.AddRange(V((ulong)key.Length));data.AddRange(key);if(!deleted){data.AddRange(V((ulong)text.Length));data.AddRange(text);}
            byte[] body=data.ToArray();var record=new List<byte>();record.AddRange(BitConverter.GetBytes(MaskedCrc(new[]{(byte)1}.Concat(body).ToArray())));record.Add((byte)body.Length);record.Add((byte)(body.Length>>8));record.Add(1);record.AddRange(body);return record.ToArray();
        }
        private static byte[] TableBlock(params KeyValuePair<byte[],byte[]>[] pairs)
        {
            var bytes=new List<byte>();byte[] prior=new byte[0];foreach(var item in pairs){int common=0;while(common<prior.Length && common<item.Key.Length && prior[common]==item.Key[common])common++;bytes.AddRange(V((ulong)common));bytes.AddRange(V((ulong)(item.Key.Length-common)));bytes.AddRange(V((ulong)item.Value.Length));bytes.AddRange(item.Key.Skip(common));bytes.AddRange(item.Value);prior=item.Key;}bytes.AddRange(BitConverter.GetBytes((uint)0));bytes.AddRange(BitConverter.GetBytes((uint)1));return bytes.ToArray();
        }
        private static byte[] StoredBlock(byte[] plain,bool snappy)
        {
            byte[] data=plain;if(snappy){var compressed=new List<byte>();compressed.AddRange(V((ulong)plain.Length));int length=plain.Length-1;if(length<60)compressed.Add((byte)(length<<2));else{int count=length<=255?1:length<=65535?2:3;compressed.Add((byte)((59+count)<<2));for(int i=0;i<count;i++)compressed.Add((byte)(length>>(8*i)));}compressed.AddRange(plain);data=compressed.ToArray();}byte[] crcBytes=data.Concat(new[]{snappy?(byte)1:(byte)0}).ToArray();return crcBytes.Concat(BitConverter.GetBytes(MaskedCrc(crcBytes))).ToArray();
        }
        private static byte[] Sst()
        {
            byte[] key=Encoding.UTF8.GetBytes("_https://synapse.invalid\0\x01synapseMacros"),value=Encoding.UTF8.GetBytes("\x01[]");
            byte[] data=StoredBlock(TableBlock(new KeyValuePair<byte[],byte[]>(key.Concat(BitConverter.GetBytes((11UL<<8)|0)).ToArray(),new byte[0]),new KeyValuePair<byte[],byte[]>(key.Concat(BitConverter.GetBytes((10UL<<8)|1)).ToArray(),value)),true);
            byte[] handle=V(0).Concat(V((ulong)data.Length-5)).ToArray();byte[] index=StoredBlock(TableBlock(new KeyValuePair<byte[],byte[]>(Encoding.UTF8.GetBytes("z"),handle)),false);
            var footer=new List<byte>();footer.AddRange(V(0));footer.AddRange(V(0));footer.AddRange(V((ulong)data.Length));footer.AddRange(V((ulong)index.Length-5));while(footer.Count<40)footer.Add(0);footer.AddRange(BitConverter.GetBytes(0xdb4775248b80fb57UL));return data.Concat(index).Concat(footer).ToArray();
        }
        private static void AdvancedTests()
        {
            MacroFixTests();
            Test("advanced-loop-and-nested-order",delegate{var child=Macro(new MacroEvent{Kind="Key",Code=46},new MacroEvent{Kind="Key",Code=46,Up=true});var root=Macro(new MacroEvent{Kind="Loop",Repeat=2,Children=new List<MacroEvent>{new MacroEvent{Kind="Macro",MacroId=child.Id,DelayMs=15}}});var plan=MacroPlan.Compile(root,new[]{root,child});Assert(plan.Count==6 && plan[0].Kind=="Delay" && plan[2].Up && plan[3].DelayMs==15,"Nested order preserved");});
            Test("advanced-missing-reference-refuses-all-input",delegate{var root=Macro(new MacroEvent{Kind="Key",Code=17},new MacroEvent{Kind="Macro",MacroId=Guid.NewGuid().ToString()});int sends=0;Throws<InvalidDataException>(()=>MacroRunner.Run(root,new[]{root},CancellationToken.None,()=>true,e=>sends++,null,null));Assert(sends==0,"Compile before first input");});
            Test("advanced-reference-cycle-rejected",delegate{var a=Macro(new MacroEvent{Kind="Delay"});var b=Macro(new MacroEvent{Kind="Macro",MacroId=a.Id});a.Events[0]=new MacroEvent{Kind="Macro",MacroId=b.Id};Throws<InvalidDataException>(()=>MacroPlan.Compile(a,new[]{a,b}));});
            Test("advanced-nested-target-restriction-preserved",delegate{var child=Macro(new MacroEvent{Kind="Key",Code=46});child.TargetProcess="fixture.exe";var root=Macro(new MacroEvent{Kind="Macro",MacroId=child.Id});Throws<InvalidDataException>(()=>MacroPlan.Compile(root,new[]{root,child}));root.TargetProcess="fixture.exe";Assert(MacroPlan.Compile(root,new[]{root,child}).Count==1,"Unified target permitted");});
            Test("advanced-expanded-duration-bound",delegate{var root=Macro(new MacroEvent{Kind="Loop",Repeat=2,Children=new List<MacroEvent>{new MacroEvent{Kind="Delay",DelayMs=600}}});root.MaxRunSeconds=1;Throws<InvalidDataException>(()=>MacroPlan.Compile(root,new[]{root}));});
            Test("advanced-expanded-action-bound",delegate{var root=Macro(new MacroEvent{Kind="Loop",Repeat=1000,Children=new List<MacroEvent>{new MacroEvent{Kind="Loop",Repeat=101,Children=new List<MacroEvent>{new MacroEvent{Kind="Key",Code=17}}}}});Throws<InvalidDataException>(()=>MacroPlan.Compile(root,new[]{root}));});
            Test("advanced-loop-F12-and-depth-checks",delegate{var e=new MacroEvent{Kind="Key",Code=0x58};Throws<InvalidDataException>(()=>Macro(new MacroEvent{Kind="Loop",Children=new List<MacroEvent>{e}}).Validate());e=new MacroEvent{Kind="Delay"};for(int i=0;i<10;i++)e=new MacroEvent{Kind="Loop",Children=new List<MacroEvent>{e}};Throws<InvalidDataException>(()=>Macro(e).Validate());});
            Test("advanced-external-actions-opt-in-before-input",delegate{var macro=Macro(new MacroEvent{Kind="Key",Code=17},new MacroEvent{Kind="Launch",ActionPath=@"C:\fixture\app.exe"});int sends=0;Throws<InvalidOperationException>(()=>MacroRunner.Run(macro,new[]{macro},CancellationToken.None,()=>true,e=>sends++,e=>sends++,null));Assert(sends==0,"Denied before execution");});
            Test("advanced-drive-relative-EXE-path-rejected",delegate{Throws<InvalidDataException>(()=>Macro(new MacroEvent{Kind="Command",ActionPath=@"C:fixture.exe"}).Validate());Throws<InvalidDataException>(()=>Macro(new MacroEvent{Kind="Command",ActionPath=@"\fixture.exe"}).Validate());Macro(new MacroEvent{Kind="Command",ActionPath=@"C:\fixture\app.exe"}).Validate();});
            Test("advanced-nested-permissions-required-at-both-levels",delegate{var child=Macro(new MacroEvent{Kind="Command",ActionPath=@"C:\fixture\app.exe"});var root=Macro(new MacroEvent{Kind="Macro",MacroId=child.Id});root.AllowExternalActions=true;Throws<InvalidOperationException>(()=>MacroPlan.Compile(root,new[]{root,child}));child.AllowExternalActions=true;root.AllowExternalActions=false;Throws<InvalidOperationException>(()=>MacroPlan.Compile(root,new[]{root,child}));root.AllowExternalActions=true;Assert(MacroPlan.Compile(root,new[]{root,child}).Count==1,"Both consented");});
            Test("advanced-actions-exercise-only-fake-receiver",delegate{var macro=Macro(new MacroEvent{Kind="Delay",DelayMs=70},new MacroEvent{Kind="Clipboard",Text="fixture only"},new MacroEvent{Kind="Launch",ActionPath=@"C:\fixture\app.exe"},new MacroEvent{Kind="Command",ActionPath=@"C:\fixture\tool.exe",Arguments="--fixture"});macro.AllowExternalActions=true;macro.AllowClipboard=true;var received=new List<string>();int waited=0;MacroRunner.Run(macro,new[]{macro},CancellationToken.None,()=>true,e=>received.Add("input"),e=>received.Add(e.Kind),n=>waited+=n);Assert(waited==70 && String.Join(",",received)=="Clipboard,Launch,Command","No production external executor used");});
            Test("advanced-clipboard-restores-original-or-empty",delegate{var clipboard=new FakeTextClipboard{Value="original fixture"};var session=new MacroClipboardSession();session.Write(clipboard,"fixture one");session.Write(clipboard,"fixture two");session.Restore(clipboard);Assert(clipboard.Value=="original fixture","Original retained across actions");clipboard.Value=null;session.Write(clipboard,"fixture one");session.Restore(clipboard);Assert(clipboard.Value==null,"Empty restored");});
            Test("advanced-clipboard-does-not-overwrite-user-copy",delegate{var clipboard=new FakeTextClipboard{Value="original fixture"};var session=new MacroClipboardSession();session.Write(clipboard,"fixture macro");clipboard.UserCopy("fixture macro");session.Restore(clipboard);Assert(clipboard.Value=="fixture macro","User copy retained even with identical text");});
            Test("advanced-clipboard-user-copy-between-actions-retained",delegate{var clipboard=new FakeTextClipboard{Value="original fixture"};var session=new MacroClipboardSession();session.Write(clipboard,"fixture macro");clipboard.UserCopy("new user copy fixture");session.Write(clipboard,"second macro text fixture");session.Restore(clipboard);Assert(clipboard.Value=="new user copy fixture","Most recent user copy restored");});
            Test("advanced-clipboard-nontext-refuses-zero-writes",delegate{var clipboard=new FakeTextClipboard{HasNonText=true};var session=new MacroClipboardSession();Throws<InvalidOperationException>(()=>session.Write(clipboard,"fixture macro"));Assert(clipboard.Writes==0,"Rich content unchanged");});
            Test("advanced-clipboard-partial-failure-still-restores",delegate{var clipboard=new FakeTextClipboard{Value="original fixture",FailWrite=true};var session=new MacroClipboardSession();Throws<IOException>(()=>session.Write(clipboard,"fixture macro"));session.Restore(clipboard);Assert(clipboard.Value=="original fixture","Partial clipboard write cleanup");});
            Test("advanced-unicode-cancellation-cleans-up",delegate{var m=Macro(new MacroEvent{Kind="Text",Text="A\u4e2d"});var cancel=new CancellationTokenSource();var sent=new List<MacroEvent>();Throws<OperationCanceledException>(()=>MacroRunner.Run(m,new[]{m},cancel.Token,()=>true,delegate(MacroEvent e){sent.Add(e);if(!e.Up)cancel.Cancel();},null,null));Assert(sent.Count==2 && sent.All(x=>x.Code=='A') && sent[1].Up,"Only first character; release guaranteed");});
            Test("advanced-partial-input-failure-cleans-up",delegate{var sent=new List<MacroEvent>();Throws<IOException>(()=>MacroRunner.Run(Macro(new MacroEvent{Kind="Key",Code=46}),CancellationToken.None,()=>true,delegate(MacroEvent e){sent.Add(e);if(!e.Up)throw new IOException("partial send");}));Assert(sent.Count==2 && sent[1].Up,"Release even if first send partially failed");});
            Test("advanced-Unicode-and-move-encoding",delegate{var u=MacroEngine.Encode(new MacroEvent{Kind="Unicode",Code=0x4e2d,Up=true});Assert(u.Data.Keyboard.Flags==6 && u.Data.Keyboard.Scan==0x4e2d,"Unicode code unit");var move=MacroEngine.Encode(new MacroEvent{Kind="Move",X=-7,Y=11});Assert(move.Data.Mouse.Flags==1 && move.Data.Mouse.X==-7 && move.Data.Mouse.Y==11,"Relative motion");});
            Test("macro-editor-local-key-message-capture",delegate{int code;bool extended;var message=System.Windows.Forms.Message.Create(IntPtr.Zero,0x100,IntPtr.Zero,new IntPtr(unchecked((long)0xffffffff811d0001UL)));Assert(MacroActionDialog.CaptureKey(message,out code,out extended) && code==29 && extended,"Signed x64 message captures scan and extended bit");message=System.Windows.Forms.Message.Create(IntPtr.Zero,0x100,IntPtr.Zero,new IntPtr(88<<16));Assert(!MacroActionDialog.CaptureKey(message,out code,out extended),"F12 excluded");message.Msg=0x101;Assert(!MacroActionDialog.CaptureKey(message,out code,out extended),"Release excluded");});
            Test("advanced-text-preview-masks-payload",delegate{var e=new MacroEvent{Kind="Clipboard",Text="fixture secret"};Assert(!e.Description().Contains(e.Text),"No text in preview");e=new MacroEvent{Kind="Command",ActionPath=@"C:\fixture\app.exe",Arguments="fixture secret"};Assert(!e.Description().Contains(e.Arguments),"No arguments in preview");});
            Test("advanced-config-roundtrip-and-legacy-identity",delegate{var m=Macro(new MacroEvent{Kind="Loop",Repeat=3,Children=new List<MacroEvent>{new MacroEvent{Kind="Text",Text="A\u4e2d"}}});var copy=CopyMacro(m);Assert(copy.Events[0].Children[0].Text=="A\u4e2d" && copy.Events[0].Repeat==3,"Nested data retained");var e=Store.Serializer().Deserialize<MacroEvent>("{\"Kind\":\"Key\",\"Code\":17,\"Identity\":\"Key:17:False\",\"Up\":true,\"DelayMs\":25}");Assert(e.Up && e.Code==17,"1.0.x data readable");});
            Test("advanced-UTF8-capacity-guard-preserves-file",delegate{Store.Save(new Settings());byte[] before=File.ReadAllBytes(Store.ConfigPath);var settings=new Settings();var macro=new MacroDefinition();string payload=new String('\u4e2d',8192);for(int i=0;i<1370;i++)macro.Events.Add(new MacroEvent{Kind="Text",Text=payload});settings.Macros.Add(macro);Throws<InvalidDataException>(()=>Store.Save(settings));Assert(File.ReadAllBytes(Store.ConfigPath).SequenceEqual(before),"Oversize rejected before replacement");});
            Test("advanced-fractional-or-unknown-fields-rejected",delegate{Throws<InvalidDataException>(()=>Store.Serializer().Deserialize<MacroEvent>("{\"Kind\":\"Key\",\"Code\":17.5}"));Throws<InvalidDataException>(()=>Store.Serializer().Deserialize<MacroEvent>("{\"Kind\":\"Key\",\"Code\":17,\"script\":\"fixture\"}"));});
            Test("advanced-file-import-revokes-permissions",delegate{string path=Path.Combine(Store.DirectoryPath,"import-fixture.json");var m=Macro(new MacroEvent{Kind="Launch",ActionPath=@"C:\fixture\app.exe"});m.AllowExternalActions=true;m.AllowClipboard=true;m.HotKey=117;Store.WriteAtomic(path,Store.Serializer().Serialize(m));var imported=MacroImport.Read(path);Assert(imported.Id!=m.Id && imported.HotKey==0 && !imported.AllowExternalActions && !imported.AllowClipboard,"New import is inactive");});
            Test("synapse-scan-flags-differ-from-HID-flags",delegate{var m=Synapse(Event("keyboard","scancode",29,"flag",2),Event("keyboard","scancode",29,"flag",3),Event("keyboard","page",7,"id",227,"flag",1),Event("keyboard","page",7,"id",227,"flag",0));Assert(m.Events[0].Extended && !m.Events[0].Up && m.Events[1].Up && m.Events[2].Code==91 && m.Events[2].Extended && !m.Events[2].Up && m.Events[3].Up,"Separate flag conventions");});
            Test("synapse-text-and-movement-preserved-inactive",delegate{var m=Synapse(Event("clipboard","text","fixture only"),Event("mouseMove","x",12,"y",34),Event("mouse","id",1),Event("mouse","id",2),Event("delay","ms",100));Assert(!m.AllowClipboard && m.HotKey==0 && m.Events[0].Kind=="Text" && m.Events[0].Text=="fixture only" && m.Events[1].Absolute && !m.Events[2].Up && m.Events[3].Up && m.Events[4].DelayMs==100,"Text Function inserts; preserves other actions without activation");});
            Test("synapse-disabled-movement-is-not-reenabled",delegate{var d=new Dictionary<string,object>{{"name","fixture"},{"guid",Guid.NewGuid().ToString()},{"appEngine",new Dictionary<string,object>{{"mouseMoveType","none"},{"events",new[]{Event("mouseMove","x",12,"y",34),Event("keyboard","scancode",46,"flag",0)}}}}};var m=SynapseImport.ConvertMacro(d);Assert(m.Events.Count==1 && m.Events[0].Kind=="Key","Disabled movement omitted intentionally");});
            Test("synapse-unknown-event-refuses-entire-macro",delegate{Throws<InvalidDataException>(()=>Synapse(Event("keyboard","scancode",46,"flag",0),Event("unknown")));});
            Test("synapse-fragment-honors-escaped-braces",delegate{string json=Store.Serializer().Serialize(new{payload=new{value="quoted \" } ] text"}});string line="[fixture] args: "+json+", suffix";Assert(SynapseImport.JsonFragment(line,line.IndexOf('{'))==json,"Exact balanced object");Throws<InvalidDataException>(()=>SynapseImport.JsonFragment("{\"x\":",0));});
            Test("synapse-empty-macro-and-F12-refused",delegate{Throws<InvalidDataException>(()=>Synapse());Throws<InvalidDataException>(()=>Synapse(Event("keyboard","scancode",88,"flag",0)));});
            Test("leveldb-snappy-overlapping-copy-and-bounds",delegate{byte[] data=LevelDbSnapshot.Snappy(new byte[]{8,0,65,13,1});Assert(Encoding.ASCII.GetString(data)=="AAAAAAAA","Overlapping copy");Throws<InvalidDataException>(()=>LevelDbSnapshot.Snappy(new byte[]{4,1,0}));Throws<InvalidDataException>(()=>LevelDbSnapshot.Snappy(new byte[]{5,0,65}));});
            Test("leveldb-WAL-latest-tombstone-read-only",delegate{string dir=Path.Combine(Store.DirectoryPath,"wal-fixture");Directory.CreateDirectory(dir);string path=Path.Combine(dir,"000001.log");byte[] original=Wal(10,false,"[]").Concat(Wal(11,true,"")).ToArray();File.WriteAllBytes(path,original);var values=LevelDbSnapshot.Read(dir);Assert(values.Count==1 && values.First().Value.Deleted && values.First().Value.Sequence==11,"Deletion authoritative");Assert(File.ReadAllBytes(path).SequenceEqual(original) && Directory.GetFiles(dir).Length==1,"Reader does not write or create locks");});
            Test("leveldb-WAL-corruption-is-not-imported",delegate{string dir=Path.Combine(Store.DirectoryPath,"wal-corrupt-fixture");Directory.CreateDirectory(dir);byte[] data=Wal(10,false,"[]");data[data.Length-1]^=1;File.WriteAllBytes(Path.Combine(dir,"000001.log"),data);Throws<InvalidDataException>(()=>LevelDbSnapshot.Read(dir));});
            Test("leveldb-compressed-SST-prefix-and-tombstone",delegate{string dir=Path.Combine(Store.DirectoryPath,"sst-fixture");Directory.CreateDirectory(dir);byte[] data=Sst();string path=Path.Combine(dir,"000001.ldb");File.WriteAllBytes(path,data);var rows=LevelDbSnapshot.Read(dir);Assert(rows.Count==1 && rows.First().Value.Deleted && rows.First().Value.Sequence==11,"Index handles, Snappy, prefix keys and deletion");Assert(File.ReadAllBytes(path).SequenceEqual(data),"SST unchanged");data[8]^=1;File.WriteAllBytes(path,data);Throws<InvalidDataException>(()=>LevelDbSnapshot.Read(dir));});
            Test("leveldb-Chromium-UTF16-decoding",delegate{Assert(LevelDbSnapshot.Decode(new byte[]{0}.Concat(Encoding.Unicode.GetBytes("[\"\u4e2d\"]")).ToArray())=="[\"\u4e2d\"]","UTF16 format");});
            Test("processor-policy-manual-transaction-preserves-DC",delegate{var api=new FakeProcessorPolicy();var before=api.Read(true);var change=ProcessorPolicyTransaction.Apply(api,before,CpuDesired(before,85,70));Assert(change.After.Maximum==85 && change.After.Epp==70 && api.Read(false).Maximum==100 && api.Read(false).Epp==90 && api.Overlay==WindowsPower.Performance && api.Activations.Count==1,"Only explicit AC settings changed");});
            Test("processor-policy-targets-effective-overlay",delegate{Guid plan=Guid.NewGuid();Assert(WindowsProcessorPolicy.Target(plan,WindowsPower.Performance)==WindowsPower.Performance && WindowsProcessorPolicy.Target(plan,WindowsPower.Efficiency)==WindowsPower.Efficiency && WindowsProcessorPolicy.Target(plan,WindowsPower.Balanced)==plan,"Overlay values take precedence");});
            Test("processor-policy-restore-is-also-verified",delegate{var api=new FakeProcessorPolicy();var before=api.Read(true);var change=ProcessorPolicyTransaction.Apply(api,before,CpuDesired(before,85,70));ProcessorPolicyTransaction.Apply(api,change.After,change.Before);Assert(api.Read(true).Maximum==100 && api.Read(true).Epp==20,"Exact original values");});
            Test("processor-policy-stale-values-refuse-zero-writes",delegate{var api=new FakeProcessorPolicy();var before=api.Read(true);api.Write(before.Plan,true,"Epp",40);int writes=api.Writes;Throws<InvalidOperationException>(()=>ProcessorPolicyTransaction.Apply(api,before,CpuDesired(before,85,70)));Assert(api.Writes==writes,"No additional writes");});
            Test("processor-policy-unknown-value-or-overlay-refuse",delegate{var api=new FakeProcessorPolicy();api.States.Values.First(x=>x.AC).Epp=null;var before=api.Read(true);Throws<InvalidOperationException>(()=>ProcessorPolicyTransaction.Apply(api,before,CpuDesired(before,85,70)));Assert(api.Writes==0,"Unknown original");api.Overlay=Guid.NewGuid();before=api.Read(true);Throws<InvalidOperationException>(()=>ProcessorPolicyTransaction.Apply(api,before,CpuDesired(before,85,null)));Assert(api.Writes==0,"Unknown overlay");});
            Test("processor-policy-partial-write-failure-restores",delegate{var api=new FakeProcessorPolicy{FailAt=2};var before=api.Read(true);Throws<IOException>(()=>ProcessorPolicyTransaction.Apply(api,before,CpuDesired(before,85,70)));var after=api.Read(true);Assert(after.Maximum==before.Maximum && after.Epp==before.Epp,"Partial original values restored");});
            Test("processor-policy-silent-write-failure-rolls-back",delegate{var api=new FakeProcessorPolicy{IgnoreAt=2};var before=api.Read(true);Throws<InvalidOperationException>(()=>ProcessorPolicyTransaction.Apply(api,before,CpuDesired(before,85,70)));Assert(api.Read(true).Maximum==100 && api.Read(true).Epp==20,"Readback mismatch cleanup");});
            Test("processor-policy-plan-race-does-not-switch-user-back",delegate{var api=new FakeProcessorPolicy();var before=api.Read(true);Guid other=Guid.NewGuid();api.AfterWrite=delegate(int n){if(n==1)api.Active=other;};Throws<InvalidOperationException>(()=>ProcessorPolicyTransaction.Apply(api,before,CpuDesired(before,85,70)));Assert(api.Active==other && api.Activations.Count==0 && api.ReadPlan(before.Plan,true).Maximum==100,"Restore only original plan values");});
            Test("processor-policy-failed-rollback-is-reported",delegate{var api=new FakeProcessorPolicy{FailAt=2,IgnoreRecovery=true};var before=api.Read(true);Throws<AggregateException>(()=>ProcessorPolicyTransaction.Apply(api,before,CpuDesired(before,85,70)));});
            Test("processor-policy-invalid-side-and-range-zero-writes",delegate{var api=new FakeProcessorPolicy();var before=api.Read(true);var desired=CpuDesired(before,85,70);desired.AC=false;Throws<InvalidOperationException>(()=>ProcessorPolicyTransaction.Apply(api,before,desired));desired.AC=true;desired.Minimum=90;Throws<InvalidOperationException>(()=>ProcessorPolicyTransaction.Apply(api,before,desired));desired.Minimum=5;desired.Maximum=101;Throws<ArgumentOutOfRangeException>(()=>ProcessorPolicyTransaction.Apply(api,before,desired));Assert(api.Writes==0,"Preflight rejected");});
            Test("nvidia-NA-current-limit-does-not-enable-watts",delegate{var gpu=NvidiaPower.Parse("fixture GPU, GPU-db0ad6d1-fcb9-6b3b-2263-116330c1ac24, 10.55, [N/A], 45, 5, 125, 46, 0, 0, 12001");Assert(!gpu.CanLimitPower && gpu.MinimumLimit==5 && gpu.MaximumLimit==125,"Bounds are not enough");Throws<NotSupportedException>(()=>NvidiaPower.SetLimit(gpu,45));});
            Test("nvidia-range-and-UUID-validation",delegate{var gpu=NvidiaPower.Parse("fixture GPU, GPU-db0ad6d1-fcb9-6b3b-2263-116330c1ac24, 10, 45, 45, 5, 125, 40, 0, 0, 12001");Throws<ArgumentOutOfRangeException>(()=>NvidiaPower.CheckLimit(gpu,126));Throws<ArgumentOutOfRangeException>(()=>NvidiaPower.CheckLimit(gpu,Double.NaN));Throws<InvalidDataException>(()=>NvidiaPower.Parse("fixture, unsafe GPU id, 10, 45, 45, 5, 125, 40, 0, 0, 1"));});
            Test("Fn-exact-device-release-expiry-and-wrap",delegate{var signal=new FnSignal{Device=@"\\?\HID#VID_1532&PID_02C5&MI_00#fixture",Down="FE0100",Up="FE0101"};signal.Validate();var state=new FnState();state.Observe(signal,"another device",signal.Down,100);Assert(!state.Active(101),"Other keyboard ignored");state.Observe(signal,signal.Device,signal.Down,100);Assert(state.Active(1999) && !state.Active(2100),"Finite state");state.Observe(signal,signal.Device,signal.Up,150);Assert(!state.Active(151),"Release clears");state.Observe(signal,signal.Device,signal.Down,Int32.MaxValue-10);Assert(!state.Active(1),"Tick wrap fails closed");});
            Test("macro-bindings-default-inactive-and-Fn-needs-signal",delegate{var macro=Macro(new MacroEvent{Kind="Delay"});var settings=new Settings();settings.Macros.Add(macro);var binding=new MacroBinding{MacroId=macro.Id,Scan=44};settings.MacroBindings.Add(binding);settings.Validate();Assert(!binding.Enabled,"Default inactive");binding.Enabled=true;Throws<InvalidDataException>(settings.Validate);binding.Modifier="CtrlAlt";settings.Validate();binding.Playback="WhileHeld";Throws<InvalidDataException>(settings.Validate);});
            Test("macro-bindings-duplicate-combo-and-F12-rejected",delegate{var macro=Macro(new MacroEvent{Kind="Delay"});var settings=new Settings();settings.Macros.Add(macro);settings.MacroBindings.Add(new MacroBinding{MacroId=macro.Id,Modifier="CtrlAlt",Scan=44,Enabled=true});settings.MacroBindings.Add(new MacroBinding{MacroId=macro.Id,Modifier="CtrlAlt",Scan=44,Enabled=true});Throws<InvalidDataException>(settings.Validate);settings.MacroBindings.RemoveAt(1);settings.MacroBindings[0].Scan=88;Throws<InvalidDataException>(settings.Validate);});
        }
    }
}
